/****** Object:  Table [dbo].[UsageDetails]    Script Date: 2/7/2023 2:55:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UsageDetails](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AdditionalInfo] [varchar](max) NULL,
	[BenefitId] [varchar](max) NULL,
	[BenefitName] [varchar](max) NULL,
	[BillingAccountId] [varchar](max) NULL,
	[BillingAccountName] [varchar](max) NULL,
	[BillingCurrencyCode] [varchar](max) NULL,
	[BillingPeriodStartDate] [date] NULL,
	[BillingPeriodEndDate] [date] NULL,
	[BillingProfileId] [varchar](max) NULL,
	[BillingProfileName] [varchar](max) NULL,
	[ChargeType] [varchar](max) NULL,
	[ConsumedService] [varchar](max) NULL,
	[CostAllocationRuleName] [varchar](max) NULL,
	[CostCenter] [varchar](max) NULL,
	[CostInBillingCurrency] [money] NULL,
	[CostInPricingCurrency] [money] NULL,
	[CostInUsd] [money] NULL,
	[CustomerName] [varchar](max) NULL,
	[CustomerTenantId] [varchar](max) NULL,
	[Date] [date] NULL,
	[EffectivePrice] [money] NULL,
	[ExchangeRate] [nvarchar](max) NULL,
	[ExchangeRateDate] [date] NULL,
	[ExchangeRatePricingToBilling] [varchar](max) NULL,
	[Frequency] [varchar](max) NULL,
	[InstanceName] [varchar](max) NULL,
	[InvoiceId] [varchar](max) NULL,
	[InvoiceSectionId] [varchar](max) NULL,
	[InvoiceSectionName] [varchar](max) NULL,
	[IsAzureCreditEligible] [varchar](max) NULL,
	[MarketPrice] [money] NULL,
	[MeterCategory] [varchar](max) NULL,
	[MeterId] [varchar](max) NULL,
	[MeterName] [varchar](max) NULL,
	[MeterRegion] [varchar](max) NULL,
	[MeterSubCategory] [varchar](max) NULL,
	[PartnerEarnedCreditApplied] [varchar](max) NULL,
	[PartnerEarnedCreditRate] [varchar](max) NULL,
	[PartnerName] [varchar](max) NULL,
	[PartnerTenantId] [varchar](max) NULL,
	[PayGPrice] [money] NULL,
	[PayGCostInBillingCurrency] [money] NULL,
	[PayGCostInUsd] [money] NULL,
	[PreviousInvoiceId] [varchar](max) NULL,
	[PricingCurrencyCode] [varchar](max) NULL,
	[PricingModel] [varchar](max) NULL,
	[Product] [varchar](max) NULL,
	[ProductIdentifier] [varchar](max) NULL,
	[ProductOrderId] [varchar](max) NULL,
	[ProductOrderName] [varchar](max) NULL,
	[Provider] [varchar](max) NULL,
	[PublisherId] [varchar](max) NULL,
	[PublisherName] [varchar](max) NULL,
	[PublisherType] [varchar](max) NULL,
	[Quantity] [decimal](18, 0) NULL,
	[ResellerMpnId] [varchar](max) NULL,
	[ResellerName] [varchar](max) NULL,
	[ReservationId] [varchar](max) NULL,
	[ReservationName] [varchar](max) NULL,
	[ResourceGroup] [varchar](max) NULL,
	[ResourceLocation] [varchar](max) NULL,
	[ResourceLocationNormalized] [varchar](max) NULL,
	[ServiceFamily] [varchar](max) NULL,
	[ServiceInfo1] [varchar](max) NULL,
	[ServiceInfo2] [varchar](max) NULL,
	[ServicePeriodEndDate] [date] NULL,
	[ServicePeriodStartDate] [date] NULL,
	[SubscriptionGuid] [varchar](max) NULL,
	[SubscriptionName] [varchar](max) NULL,
	[Tags] [varchar](max) NULL,
	[Term] [varchar](max) NULL,
	[UnitOfMeasure] [varchar](max) NULL,
	[UnitPrice] [money] NULL,
 CONSTRAINT [PK_UsageDetails_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

